mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls')),
    path('news/', include('news.urls')),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('scrape/', views.scrape, name="scrape"),
    path('list/', views.news_list, name="list")
]

notes/urls.py
from django.urls import path
from . import views


app_name = 'notes'
urlpatterns = [
    path('', views.list_notes, name='list',),
    path('create/', views.create_notes, name='create'),
    path('<int:id>/delete/', views.delete_notes, name='delete'),
    path('<int:id>/update/', views.update_notes, name='update'),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Headline(models.Model):
    title = models.CharField(max_length=120)
    image = models.ImageField(null=True, blank=True)
    url = models.TextField()

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    last_scrape = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.user} - {self.last_scrape}'

notes/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    image = models.ImageField(null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

notes/forms.py
from django import forms
from .models import Note


class NotesModelForm(forms.ModelForm):
    class Meta:
        model = Note
        exclude = ['user', 'timestamp']

news/views.py
from django.shortcuts import render, redirect
import urllib3
import requests
from bs4 import BeautifulSoup
from .models import Headline, UserProfile
from datetime import datetime, timezone

urllib3.disable_warnings()


def news_list(request):

    all_news = Headline.objects.all()
    context = {
        'all_news': all_news
    }
    return render(request, 'news/news_list.html', context)


def scrape(request):

    user_p = UserProfile()
    user_p.user = request.user
    user_p.last_scrape = datetime.now(timezone.utc)
    user_p.save()

    session = requests.Session()
    session.headers = {"User-Agent": "Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 "
                                     "(KHTML, like Gecko) Mobile/7B405Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS "
                                     "X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405"}

    url = 'https://www.theonion.com/'
    content = session.get(url, verify=False).content

    soup = BeautifulSoup(content, "html.parser")

    section = soup.find('div', {'class': 'sc-1plvju9-0 fGFCYh'})

    titles = section.find_all_next('h4', {'class': 'kbLSgc'})
    links = [l.parent.get('href') for l in titles]

    for title, link in zip(titles, links):
        headline = Headline()
        headline.title = title.text
        headline.url = link
        headline.save()

    return redirect('/')

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import NotesModelForm
from .models import Note


# Create your views here.
def create_notes(request):
    if request.method == 'POST':
        form = NotesModelForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('/notes/')
    else:
        form = NotesModelForm()
    context = {
        'form': form,
        'naming': 'Create'
    }
    return render(request, 'notes/notes_form.html', context)


def list_notes(request):
    all_notes = Note.objects.all()
    context = {
        'all_notes': all_notes
    }
    return render(request, 'notes/notes_list.html', context)


def delete_notes(request, id):
    note_to_delete = get_object_or_404(Note, pk=id)
    if request.user == note_to_delete.user:
        note_to_delete.delete()
    return redirect('/notes/')


def update_notes(request, id):
    note_to_update = get_object_or_404(Note, pk=id)
    if request.method == 'POST':
        form = NotesModelForm(request.POST or None, request.FILES or None, instance=note_to_update)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('/notes/')
    else:
        form = NotesModelForm(instance=note_to_update)
    context = {
        'form': form,
        'naming': 'Update'
    }
    return render(request, 'notes/notes_form.html', context)

news/templates/news/news_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <h1>Get The News</h1>
    <form action="{% url 'news:scrape' %}" method="POST">
        {% csrf_token %}
        <button type="submit">Get News</button>
    </form>

    <h1>List News</h1>
    <ul>
        {% for news in all_news %}
        <li><p>{{ news }}</p><a href="{{ news.url }}">Check</a></li>
        <br>
        {% endfor %}
    </ul>

</body>
</html>

notes/templates/notes/notes_form.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{{ naming }}</button>
</form>

</body>
</html>

notes/templates/notes/notes_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<ul>
    {% for note in all_notes %}
        <li>
            {{ note }}
            <a href="{% url 'notes:update' note.id %}">Update</a>
            <a href="{% url 'notes:delete' note.id %}">Delete</a>
        </li>
    {% endfor %}
</ul>
</body>
</html>